# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'fileBrowser-zxkit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for fileBrowser-zxkit
 	pod 'ZXKitCore', '~> 2.0.0'
	pod 'ZXFileBrowser', '~> 2.0.0'
end
