# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'DDKitSwift_FileBrowser' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DDKitSwift_FileBrowser
 	pod 'DDKitSwift/core', '~> 3'
	pod 'DDFileBrowser', '~> 3'
end
